nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:3001']
    allow_credentials: true
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    max_age: 3600

  paths:
    '^/api/':
      allow_origin: ['http://localhost:3001']
