<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250425183453 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE MTC_CATEGORIE (CAT_ID INT AUTO_INCREMENT NOT NULL, CAT_LABEL VARCHAR(255) NOT NULL, PRIMARY KEY(CAT_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE MTC_HOTEL (HTL_ID INT AUTO_INCREMENT NOT NULL, HTL_NAME VARCHAR(255) NOT NULL, HTL_ADRESS VARCHAR(255) NOT NULL, HTL_CODE_POSTAL VARCHAR(255) NOT NULL, HTL_CITY VARCHAR(255) NOT NULL, HTL_COUNTRY VARCHAR(255) NOT NULL, HTL_DESCRIPTION VARCHAR(255) NOT NULL, HTL_CHILDREN TINYINT(1) NOT NULL, HTL_ANIMAL TINYINT(1) NOT NULL, HTL_TYPE_CITY VARCHAR(255) NOT NULL, HTL_TRANSPORT JSON NOT NULL, HTL_RESTORATION VARCHAR(255) NOT NULL, HTL_WELLNESS JSON NOT NULL, HTL_BUSINESS_SERVICE JSON NOT NULL, HTL_COMFORT JSON NOT NULL, HTL_ADD_SERVICES JSON NOT NULL, HTL_PMR TINYINT(1) NOT NULL, HTL_BABY TINYINT(1) NOT NULL, USR_ID INT DEFAULT NULL, CAT_ID INT DEFAULT NULL, INDEX IDX_A2A6B370C4DC529D (USR_ID), INDEX IDX_A2A6B3702E182825 (CAT_ID), PRIMARY KEY(HTL_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE MTC_NEGOCIATION (NEG_ID INT AUTO_INCREMENT NOT NULL, NEG_REQUESTED_PRICE INT NOT NULL, NEG_STATUS VARCHAR(255) NOT NULL, NEG_CREATED_AT DATETIME NOT NULL, NEG_RESPONSE_AT DATETIME NOT NULL, NEG_CHALLENGE_PRICE INT DEFAULT NULL, NEG_IS_CLOSE TINYINT(1) NOT NULL, NEG_START_DATE DATETIME NOT NULL, NEG_END_DATE DATETIME NOT NULL, USR_ID INT DEFAULT NULL, ROOM_ID INT DEFAULT NULL, INDEX IDX_C24C62D4C4DC529D (USR_ID), INDEX IDX_C24C62D4531FC869 (ROOM_ID), PRIMARY KEY(NEG_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE MTC_PAYMENT (PAY_ID INT AUTO_INCREMENT NOT NULL, PAY_STRIPE_ID INT NOT NULL, PAY_AMOUNT INT NOT NULL, PAY_STATUS VARCHAR(255) NOT NULL, PAY_METHOD VARCHAR(255) NOT NULL, PAY_RECEIPT VARCHAR(255) NOT NULL, PAY_CREATED_AT DATETIME NOT NULL, USR_ID INT DEFAULT NULL, INDEX IDX_62BCB8F7C4DC529D (USR_ID), PRIMARY KEY(PAY_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE MTC_RESERVATION (RES_ID INT AUTO_INCREMENT NOT NULL, RES_CREATED_AT DATETIME NOT NULL, RES_START_DATE DATETIME NOT NULL, RES_END_DATE DATETIME NOT NULL, RES_PRICE INT NOT NULL, RES_STATUS VARCHAR(255) NOT NULL, USR_ID INT DEFAULT NULL, ROOM_ID INT DEFAULT NULL, INDEX IDX_35651C59C4DC529D (USR_ID), INDEX IDX_35651C59531FC869 (ROOM_ID), PRIMARY KEY(RES_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE MTC_ROOM (ROOM_ID INT AUTO_INCREMENT NOT NULL, ROOM_NAME VARCHAR(255) NOT NULL, ROOM_DESCRIPTION LONGTEXT NOT NULL, ROOM_BASE_PRICE INT NOT NULL, ROOM_MAX_GUESTS INT NOT NULL, HTL_ID INT DEFAULT NULL, INDEX IDX_56E1861A7972BF64 (HTL_ID), PRIMARY KEY(ROOM_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE MTC_THRESHOLD (THR_ID INT AUTO_INCREMENT NOT NULL, THR_MINIMUM INT NOT NULL, THR_MAXIMUM INT NOT NULL, THR_START_DATE DATETIME NOT NULL, THR_END_DATE DATETIME NOT NULL, HTL_ID INT DEFAULT NULL, INDEX IDX_84AC54D87972BF64 (HTL_ID), PRIMARY KEY(THR_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE MTC_USER (USR_ID INT AUTO_INCREMENT NOT NULL, USR_NAME VARCHAR(30) NOT NULL, USR_FIRSTNAME VARCHAR(100) NOT NULL, USR_EMAIL VARCHAR(255) NOT NULL, USR_PASSWORD VARCHAR(255) NOT NULL, USR_RESET_TOKEN VARCHAR(255) NOT NULL, USR_ROLE JSON NOT NULL, USR_CREATED_AT DATETIME NOT NULL, PRIMARY KEY(USR_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE MTC_LIKE (USR_ID INT NOT NULL, ROOM_ID INT NOT NULL, INDEX IDX_881D9732C4DC529D (USR_ID), INDEX IDX_881D9732531FC869 (ROOM_ID), PRIMARY KEY(USR_ID, ROOM_ID)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_HOTEL ADD CONSTRAINT FK_A2A6B370C4DC529D FOREIGN KEY (USR_ID) REFERENCES MTC_USER (USR_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_HOTEL ADD CONSTRAINT FK_A2A6B3702E182825 FOREIGN KEY (CAT_ID) REFERENCES MTC_CATEGORIE (CAT_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_NEGOCIATION ADD CONSTRAINT FK_C24C62D4C4DC529D FOREIGN KEY (USR_ID) REFERENCES MTC_USER (USR_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_NEGOCIATION ADD CONSTRAINT FK_C24C62D4531FC869 FOREIGN KEY (ROOM_ID) REFERENCES MTC_ROOM (ROOM_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_PAYMENT ADD CONSTRAINT FK_62BCB8F7C4DC529D FOREIGN KEY (USR_ID) REFERENCES MTC_USER (USR_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_RESERVATION ADD CONSTRAINT FK_35651C59C4DC529D FOREIGN KEY (USR_ID) REFERENCES MTC_USER (USR_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_RESERVATION ADD CONSTRAINT FK_35651C59531FC869 FOREIGN KEY (ROOM_ID) REFERENCES MTC_ROOM (ROOM_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_ROOM ADD CONSTRAINT FK_56E1861A7972BF64 FOREIGN KEY (HTL_ID) REFERENCES MTC_HOTEL (HTL_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_THRESHOLD ADD CONSTRAINT FK_84AC54D87972BF64 FOREIGN KEY (HTL_ID) REFERENCES MTC_HOTEL (HTL_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_LIKE ADD CONSTRAINT FK_881D9732C4DC529D FOREIGN KEY (USR_ID) REFERENCES MTC_USER (USR_ID)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_LIKE ADD CONSTRAINT FK_881D9732531FC869 FOREIGN KEY (ROOM_ID) REFERENCES MTC_ROOM (ROOM_ID)
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_HOTEL DROP FOREIGN KEY FK_A2A6B370C4DC529D
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_HOTEL DROP FOREIGN KEY FK_A2A6B3702E182825
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_NEGOCIATION DROP FOREIGN KEY FK_C24C62D4C4DC529D
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_NEGOCIATION DROP FOREIGN KEY FK_C24C62D4531FC869
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_PAYMENT DROP FOREIGN KEY FK_62BCB8F7C4DC529D
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_RESERVATION DROP FOREIGN KEY FK_35651C59C4DC529D
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_RESERVATION DROP FOREIGN KEY FK_35651C59531FC869
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_ROOM DROP FOREIGN KEY FK_56E1861A7972BF64
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_THRESHOLD DROP FOREIGN KEY FK_84AC54D87972BF64
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_LIKE DROP FOREIGN KEY FK_881D9732C4DC529D
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE MTC_LIKE DROP FOREIGN KEY FK_881D9732531FC869
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MTC_CATEGORIE
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MTC_HOTEL
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MTC_NEGOCIATION
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MTC_PAYMENT
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MTC_RESERVATION
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MTC_ROOM
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MTC_THRESHOLD
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MTC_USER
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE MTC_LIKE
        SQL);
    }
}
